version: '3.8'
services:
  musicapp-backend:
    build:
      context: ./musicapp-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: 'jdbc:postgresql://db:5432/postgres' # Ensure connection with db service within Docker
      DB_USERNAME: 'user'
      DB_PASSWORD: 'pass'
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_SERVLET_CONTEXT_PATH: /api/musicapp # Context path of application
    depends_on:
      - db

  musicapp-frontend:
    build:
      context: ./musicapp-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists db data
    ports:
      - "5432:5432" # Expose db on port 5432

volumes:
  postgres_data: # Define volume for db data