spring:
  application:
    name: musicapp-backend
  datasource:
    url: "${db.url:jdbc:postgresql://localhost:5432/postgres}"
    username: "${db.username:user}"
    password: "${db.password:pass}"
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: WARN
    com.ice.musicappbackend: DEBUG
server:
  servlet:
    context-path: /api/musicapp
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
